name: "Check"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled

jobs:
  Check-again:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3