name: "PR Title Validation (Linear-Based)"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled

jobs:
  PR-title-linear-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Title validation
        id: validate
        uses: swe-memory/linear-actions@v2.0
        with:
          token: ${{ github.token }}
          linear_auth_type: "accessToken"
          linear_auth_key: ${{ secrets.LINEAR_OAUTH }}